### ISSUE TITLE
Global named bid isn't defined

### ISSUE THREAD

**Issue by fwilson42** [fwilson42/ibot2#3]
Traceback (most recent call last):
  File "ibottest.py", line 5, in <module>
    bids = Iodine.getAllBids(auth)
  File "/home/fox-wilson/projects/intrabot2/Block.py", line 68, in getAllBids
    return [Block(authObj, bid=i) for i in bids.keys()]
  File "/home/fox-wilson/projects/intrabot2/Block.py", line 31, in **init**
    self.bid = str(bid)
NameError: global name 'bid' is not defined

**Comment by fwilson42** [comment]
functionality is implemented in ion
